let uname = 'John';
let age = 18;
let abc = false;
let abc2 = null;
let abc3 = undefined;
let abc4 = 'WenLong';
abc4 = 20;
abc4 = true;
let abc5 = ['a', 'b', 'c'];
let abc6 = [1, 2, 3, 4];
console.log(`${uname}:${age}:${abc}:${abc2}:${abc3}:${abc4}:${abc5}:${abc6}`);
